<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function idplates_labelbuilder_menu() {
  $items = array();

  $items['labelbuilder/size/%node'] = array(
    'title' => 'Label Builder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idplates_labelbuilder_size_form', 2),
    'access arguments' => array('access content'),
    'file' => 'includes/idplates_labelbuilder.sizes.inc',
  );

  $items['labelbuilder/layout/%commerce_product'] = array(
    'title' => 'Label Builder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idplates_labelbuilder_layout_form', 2),
    'access arguments' => array('access content'),
    'file' => 'includes/idplates_labelbuilder.layouts.inc',
  );

  $items['labelbuilder/customize/%taxonomy_term'] = array(
    'title' => 'Label Builder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idplates_labelbuilder_customize_form', 2),
    'access arguments' => array('access content'),
    'file' => 'includes/idplates_labelbuilder.customize.inc',
  );

  $items['labelbuilder/options'] = array(
    'title' => 'Label Builder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idplates_labelbuilder_options_form'),
    'access arguments' => array('access content'),
    'file' => 'includes/idplates_labelbuilder.options.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function idplates_labelbuilder_theme($existing, $type, $theme, $path) {
  return array(
    'idplates_labelbuilder_preview' => array(
      'template' => 'idplates-labelbuilder-preview',
      'path' => drupal_get_path('module', 'idplates_labelbuilder') . '/templates',
      'arguments' => array(
        'label' => NULL,
      ),
    ),
    'idplates_labelbuilder_size' => array(
      'template' => 'idplates-labelbuilder-size',
      'path' => drupal_get_path('module', 'idplates_labelbuilder') . '/templates',
      'arguments' => array(
        'path' => NULL,
        'size' => NULL,
        'attributes' => NULL,
      ),
    ),
    'idplates_labelbuilder_layout' => array(
      'template' => 'idplates-labelbuilder-layout',
      'path' => drupal_get_path('module', 'idplates_labelbuilder') . '/templates',
      'arguments' => array(
        'path' => NULL,
        'sku' => NULL,
        'attributes' => NULL,
      ),
    ),
  );
}

/**
 *
 */
function idplates_labelbuilder_get_label($size, $layout) {
  $query = db_select('field_data_field_label_size', 'b');
  $query->join('field_data_field_layout_options', 'y', 'b.entity_id = y.entity_id');
  $query
    ->condition('b.field_label_size_tid', $size)
    ->condition('y.field_layout_options_target_id', $layout)
    ->fields('b', array('entity_id'));

  $results = $query->execute()->fetchAssoc();

  return $results;
}

function idplates_labelbuilder_add_to_cart($product, $uid = 0) {
  $line_item = commerce_product_line_item_new($product);
  $line_item = commerce_cart_product_add($uid, $line_item, FALSE);
  return $line_item;
}

function idplates_label_builder_get_label_preview(&$form, &$form_state) {
  $form['column_right']['label_proof'] = array(
    '#type' => 'fieldset',
    '#title' => t('Label Proof'),
  );
  $form['column_right']['label_proof']['preview'] = array(
    '#type' => 'item',
    '#prefix' => '<div id="idplates-labelbuilder-preview-ajax-wrapper">',
    '#suffix' => '</div>',
    '#markup' => theme('idplates_labelbuilder_preview', array(
      'label' => $form_state['label'],
    )),
  );
  $form['column_right']['label_proof']['qty'] = array(
    '#type' => 'textfield',
    '#title' => t('Quantity'),
    '#ajax' => array(
      'callback' => 'idplates_label_builder_live_price_ajax_callback',
      'wrapper' => 'idplates-labelbuilder-live-price-ajax-wrapper',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
  $form['column_right']['label_proof']['live_price'] = array(
    '#type' => 'item',
    '#markup' => 'live price',
  );

}

function idplates_label_builder_live_price_ajax_callback($form, $form_state) {
  return $form['column_right']['label_proof']['live_price'];
}

function idplates_label_builder_preview_ajax_callback($form, $form_state) {
  return $form['column_right']['label_proof']['preview'];
}
